export type Shift = 'day' | 'night';
export type QualityFlag = 'MISSING_VITALS' | 'IMPLAUSIBLE_BP' | 'IMPLAUSIBLE_VITAL' | 'UNEXPECTED_TEMPERATURE_UNIT' | 'DUPLICATE_REPORT' | 'REPEATED_IDENTICAL_VITALS' | 'PARSE_WARNING' | 'AMBIGUOUS_SLOT' | 'UNEXPECTED_REPORTER' | 'OUTSIDE_EXPECTED_SCHEDULE';
export type EscalationStatus = 'NO_ESCALATION_REQUIRED' | 'ESCALATED_WITHIN_SLA' | 'ESCALATED_LATE' | 'NOT_TAGGED' | 'NO_SUPERVISOR_RESPONSE' | 'INVALID_READING_REQUIRES_VALIDATION';
export interface RawMessage { id: string; at: number; sender: string; text: string; line: number; }
export interface VitalSet { systolic?: number; diastolic?: number; pulse?: number; temperature?: number; temperatureUnit?: 'C' | 'F' | 'unspecified'; spo2?: number; }
export interface OperationalEvent { id: string; type: 'pause' | 'resume' | 'coverage'; client: string; at: number; messageId: string; caregiver?: string; endDate?: string; }
export interface ExpectedSlot { id: string; client: string; shift: Shift; time: string; due: number; caregiver: string; paused: boolean; pauseEvidence?: string; reportId?: string; }
export interface Report { id: string; messageId: string; sentAt: number; sender: string; client: string; statedTime?: string; due?: number; slotId?: string; shift?: Shift; vitals: VitalSet; narrative: string; flags: QualityFlag[]; flagReasons: string[]; complete: boolean; abnormal: string[]; dataIntegrityCritical: boolean; duplicateOf?: string; minutesFromDue?: number; onTime?: boolean; escalation: EscalationStatus; tagged: boolean; supervisorMessageId?: string; supervisorMinutes?: number; followupMessageId?: string; }
export interface Aggregate { name: string; expected: number; received: number; onTime: number; complete: number; missing: number; late: number; escalationIssues: number; quality: number; }
export interface ActionItem { severity: 'critical' | 'high' | 'review' | 'positive'; title: string; detail: string; reportId?: string; slotId?: string; messageId?: string; }
export interface Analysis { messages: RawMessage[]; reports: Report[]; events: OperationalEvent[]; slots: ExpectedSlot[]; clients: Aggregate[]; caregivers: Aggregate[]; actions: ActionItem[]; kpis: { completion: number; onTime: number; completeVitals: number; escalation: number; quality: number; }; received: number; missing: number; late: number; validAbnormal: number; warnings: string[]; }
