import { readFileSync } from 'node:fs';
import path from 'node:path';
import Link from 'next/link';
import { analyze } from '../../domain/analyze';
import { PrintButton } from '../../components/print-button';

export default function AnalysisPage() {
  const result = analyze(readFileSync(path.join(process.cwd(), 'Sample_Homecare_WhatsApp_Export.txt'), 'utf8'));
  const active = result.slots.filter(s => !s.paused).length;
  const complete = result.reports.filter(r => r.slotId && result.slots.find(s => s.id === r.slotId)?.reportId === r.id && r.complete).length;
  const abnormal = result.reports.filter(r => r.slotId && !r.duplicateOf && r.abnormal.length);
  const within = abnormal.filter(r => r.escalation === 'ESCALATED_WITHIN_SLA').length;
  const quality = result.reports.filter(r => r.slotId && result.slots.find(s => s.id === r.slotId)?.reportId === r.id && r.flags.length).length;
  const missed = result.reports.find(r => r.client === 'HC-01' && r.vitals.systolic === 182);
  const met = result.reports.find(r => r.client === 'HC-04' && r.vitals.spo2 === 88);
  return <div className="print-page"><div className="print-toolbar no-print"><Link href="/">← Operations</Link><PrintButton/></div><div className="print-banner"><span>CARE360 / XALCO LTD</span><span>EXECUTIVE AUDIT · 21 SEP 2026</span></div><h1>Homecare reporting: operational analysis</h1><p className="print-lede">7–20 September 2026 · WhatsApp export analysis · synthetic assessment data</p>
    <section><h2>Problem statement</h2><p>Caregivers submit vital signs and care notes in a shared WhatsApp group. Nurse supervisors and managers must recognize missed reports, abnormal readings and escalation failures by reading a noisy conversation manually. The group offers no reliable expected-slot denominator, systematic timeliness history or source-linked exception queue. Care360 Signal turns the export into scheduled, validated and auditable records so management can prioritize follow-up.</p></section>
    <section><h2>As-Is → To-Be</h2><div className="process-grid"><div><strong>AS-IS · MANUAL</strong><p>Caregiver → WhatsApp group → human back-scroll → manual abnormal recognition → ad hoc escalation → no dependable compliance history</p></div><div><strong>TO-BE · CONTROLLED</strong><p>Report source → parser → validation and schedule matching → clinical thresholds → escalation clock → exception queue → manager review and raw-message audit</p></div></div></section>
    <section><h2>Five operational KPIs</h2><div className="print-kpis"><div><strong>1 · Reporting completion</strong><p>Unique received active slots / all active slots. <b>{result.received}/{active} = {result.kpis.completion}%</b></p></div><div><strong>2 · On-time reporting</strong><p>First report within ±30 min / all active slots. <b>{result.clients.reduce((sum, client) => sum + client.onTime, 0)}/{active} = {result.kpis.onTime}%</b></p></div><div><strong>3 · Complete vitals</strong><p>Received reports with BP, pulse, Celsius temp and SpO₂ / unique received. <b>{complete}/{result.received} = {result.kpis.completeVitals}%</b></p></div><div><strong>4 · Escalation SLA</strong><p>Valid abnormal reports tagged and answered within 15 min / all valid abnormal reports. <b>{within}/{abnormal.length} = {abnormal.length ? `${result.kpis.escalation}%` : '—'}</b></p></div><div><strong>5 · Data-quality exceptions</strong><p>Unique received reports with ≥1 quality flag / unique received. <b>{quality}/{result.received} = {result.kpis.quality}%</b></p></div></div></section>
    <div className="page-break"/>
    <section><h2>Prioritized findings and action</h2><ol className="findings"><li><strong>Review the failed HC-01 escalation first.</strong> On 15 September a BP 182/112 report was sent at about 15:22 without a supervisor tag. The matched response came {missed?.supervisorMinutes ?? '—'} minutes later. Reconcile handoff, calling practice and supervisor monitoring against the original messages.</li><li><strong>Correct recurring missing slots.</strong> {result.missing} of {active} active reports are missing. HC-04 has {result.slots.filter(s => s.client === 'HC-04' && s.time === '15:00' && !s.reportId).length} absent 15:00 slots; HC-02 has {result.clients.find(c => c.name === 'HC-02')?.missing} missing night reports, concentrated at 00:00, 02:00 and 04:00. Review staffing and handover coverage.</li><li><strong>Improve punctuality and completeness.</strong> {result.late} received reports were late; {result.received - complete} unique scheduled reports lack the complete required Celsius vital set. Coach the affected caregivers and check whether network outages need a documented fallback.</li><li><strong>Validate measurement practice and data entry.</strong> The original export includes BP 1300/86, temperature 99.1°F, a duplicate report and a long HC-03 day-shift run of identical readings. These are verification prompts, not diagnoses or allegations.</li><li><strong>Retain the successful response as a training example.</strong> On 17 September HC-04 SpO₂ 88% was tagged and answered in {met?.supervisorMinutes ?? '—'} minutes; a subsequent recheck is documented.</li></ol></section>
    <section><h2>Interpretation and production path</h2><p>Slots are generated from the brief; five HC-05 slots are excluded during supervisor-confirmed hospitalization. The ±30-minute window is inclusive. The inferred caregiver roster should be checked against Care360 scheduling. Each flag points to the original WhatsApp line. The prototype processes files locally in the browser. For live use: WhatsApp Business Cloud API → signature-verified webhook → encrypted raw event store and idempotency key → queue with retries/dead-letter handling → parser and rule worker → operational database → role-scoped dashboard and supervisor notification. Apply minimal data retention, audit logs and monitoring.</p></section><footer className="print-footer">CARE360 SIGNAL · Assessment analysis · Deterministic rules with source evidence</footer>
  </div>;
}
